### ISSUE TITLE
Permission to Modify/Adapt?

### ISSUE THREAD

**Issue by nicholaelaw** [CloudflareApps/SideNav#1]
Hi there, just found sidenav and love it. I want to make some modifications such as moving the sidebar to the right and changing the spacing between text, etc. So I'm asking for your permission to modify it, and install it directly on my blog. I'm asking because I didn't see license info.

**Comment by adamschwartz** [comment]
Thanks! Yup, it’s now [MIT License](https://github.com/EagerApps/SideNav/blob/master/LICENSE). Enjoy!

The specific feature of allowing it to be positioned on the right would be great for the [Eager app](https://eager.io/app/sidenav/install) as well, so if you’d like to PR that back in, we’d be all for it. :+1:

**Comment by adamschwartz** [comment]
@nicholaelaw btw thanks to @markrabey’s https://github.com/EagerApps/SideNav/pull/2, we now support positioning on the right. https://github.com/EagerApps/SideNav/commit/dfd32e0cfa79aede8eb4c2567692961b4e848100
